name: "Sphinx: Render docs"

on: 
  push:
    branches: [ sphinx ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "sphinx/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: sphinx/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/sphinx'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: sphinx/_build/html

